# Generated by Django 4.0 on 2022-01-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('case_nr', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('crime_type', models.CharField(max_length=255)),
            ],
        ),
    ]
