DRUGS_AND_PRECURSORS = {
    "safrol": ['safrol', 'isosafrol', 'safrool', 'isosafrool'],
    "piperonal": ['piperonal', 'piperonalglycidaat'],
    "PMK": ['PMK','piperonylmethylketon'],
    "BMK": ['BMK', 'BenzylMethylKeton', "MAPA", "APAA", "APAAN", "benzaldehyde", "benzylcyanide", "P2NP"],
    "apaan": ['apaan','Alpha-Phenylacetoacetonitrile', 'AlphaPhenylacetoacetonitrile'],
    "GBL": ['GBL', 'Gamma-butyrolacton'],
    "MDP2P": ['MDP2P'],
    "efedrine": ['Efedrine', 'Ephedrine'],
    "ergotamine": ['Ergotamine'],
    "lyserginezuur": ['Lyserginezuur'],
    "methamphetamine": ['Methamfetamine', 'Methamphetamine', 'Meth'],
    "MDMA": ['MDMA', 'Methylenedioxymethamphetamine'],
    "amphetamine": ['Amfetamine', 'Amphetamine'],
    "cocaine": ['Cocaïne', 'Cocaine', 'Coke'],
    "XTC": ['XTC', 'ecstasy'],
    "GHB": ['GHB', 'gamma-hydroxyboterzuur', '4-hydroxybutaanzuur'],
}


GERECHTSCODE_LOCATIE_MAPPING = {
    'AGAMS': 'Amsterdam',
    'AGARN': 'Arnhem',
    'AGGRO': 'Groningen',
    'AGHAA': 'Haarlem',
    'AGROE': 'Roermond',
    'AGROT': 'Rotterdam',
    'AGSGR': "'s-Gravenhage",
    'AGSHE': "'s-Hertogenbosch",
    'AGUTR': 'Utrecht',
    'AGZWO': 'Zwolle',
    'CBB': 'Den Haag',
    'CRVB': 'Beroep',
    'CVBSTUF': 'Studiefinanciering',
    'DETARCO': 'Tariefcommissie',
    'GHAMS': 'Amsterdam',
    'GHARL': 'Arnhem-Leeuwarden',
    'GHARN': 'Arnhem',
    'GHDHA': 'Den Haag',
    'GHLEE': 'Leeuwarden',
    'GHSGR': "'s-Gravenhage",
    'GHSHE': "'s-Hertogenbosch",
    'HR': 'Hoge Raad',
    'KTGAAR': 'Alphen aan de Rijn',
    'KTGALK': 'Alkmaar',
    'KTGALM': 'Almelo',
    'KTGAMF': 'Amersfoort',
    'KTGAMS': 'Amsterdam',
    'KTGAPD': 'Apeldoorn',
    'KTGARN': 'Arnhem',
    'KTGASS': 'Assen',
    'KTGBEE': 'Beetsterzwaag',
    'KTGBOX': 'Boxmeer',
    'KTGBOZ': 'Zoom',
    'KTGBRE': 'Breda',
    'KTGBRI': 'Brielle',
    'KTGDEL': 'Delft',
    'KTGDEV': 'Deventer',
    'KTGDHD': 'Helder',
    'KTGDOR': 'Dordrecht',
    'KTGEIN': 'Eindhoven',
    'KTGEMM': 'Emmen',
    'KTGENS': 'Enschede',
    'KTGGNL': 'Groenlo',
    'KTGGOU': 'Gouda',
    'KTGGRC': 'Gorinchem',
    'KTGGRO': 'Groningen',
    'KTGHAA': 'Haarlem',
    'KTGHAR': 'Harderwijk',
    'KTGHFD': 'Hoofddorp',
    'KTGHIL': 'Hilversum',
    'KTGHMD': 'Helmond',
    'KTGHRL': 'Heerlen',
    'KTGHRN': 'Hoorn',
    'KTGHRV': 'Heerenveen',
    'KTGLDN': 'Leiden',
    'KTGLEE': 'Leeuwarden',
    'KTGLLY': 'Lelystad',
    'KTGMAA': 'Maastricht',
    'KTGMEP': 'Meppel',
    'KTGMID': 'Middelburg',
    'KTGNMG': 'Nijmegen',
    'KTGOBL': 'Oud-Beijerland',
    'KTGOOS': 'Oostburg',
    'KTGPAR': 'Parimaribo',
    'KTGROE': 'Roermond',
    'KTGROT': 'Rotterdam',
    'KTGSCH': 'Schiedam',
    'KTGSGR': "'s-Gravenhage",
    'KTGSHE': "'s-Hertogenbosch",
    'KTGSIT': 'Sittard',
    'KTGSNK': 'Sneek',
    'KTGSOM': 'Sommelsdijk',
    'KTGSTW': 'Steenwijk',
    'KTGTIE': 'Tiel',
    'KTGTIL': 'Tilburg',
    'KTGTRB': 'Terborg',
    'KTGTRN': 'Terneuzen',
    'KTGUTR': 'Utrecht',
    'KTGVEE': 'Veendam',
    'KTGVEN': 'Venlo',
    'KTGWAG': 'Wageningen',
    'KTGWIN': 'Winschoten',
    'KTGZAA': 'Zaandam',
    'KTGZEV': 'Zevenbergen',
    'KTGZIE': 'Zierikzee',
    'KTGZUI': 'Zuidbroek',
    'KTGZUT': 'Zutphen',
    'KTGZWO': 'Zwolle',
    'OCHM': 'Sint Maarten',
    'OGAACMB': 'Saba',
    'OGANA': 'Antillen',
    'OGEAA': 'Aruba',
    'OGEAB': 'Bonaire',
    'OGEABES': 'Saba',
    'OGEAC': 'Curacao',
    'OGEAM': 'Maarten',
    'OGEANA': 'Antillen',
    'OGHACMB': 'Saba',
    'OGHNAA': 'Aruba',
    'OHJNA': 'Antillen',
    'ORBAACM': 'Saba',
    'ORBANAA': 'Aruba',
    'ORBBACM': 'Saba',
    'ORBBNAA': 'Aruba',
    'PHR': 'Parket bij de Hoge Raad',
    'RBALK': 'Alkmaar',
    'RBALM': 'Almelo',
    'RBAMS': 'Amsterdam',
    'RBARN': 'Arnhem',
    'RBASS': 'Assen',
    'RBBRE': 'Breda',
    'RBDHA': 'Haag',
    'RBDOR': 'Dordrecht',
    'RBGEL': 'Gelderland',
    'RBGRO': 'Groningen',
    'RBHAA': 'Haarlem',
    'RBLEE': 'Leeuwarden',
    'RBLIM': 'Limburg',
    'RBMAA': 'Maastricht',
    'RBMID': 'Middelburg',
    'RBMNE': 'Midden-Nederland',
    'RBNHO': 'Noord-Holland',
    'RBNNE': 'Noord-Nederland',
    'RBOBR': 'Oost-Brabant',
    'RBONE': 'Oost-Nederland',
    'RBOVE': 'Overijssel',
    'RBROE': 'Roermond',
    'RBROT': 'Rotterdam',
    'RBSGR': "'s-Gravenhage",
    'RBSHE': "'s-Hertogenbosch",
    'RBUTR': 'Utrecht',
    'RBZLY': 'Zwolle-Lelystad',
    'RBZUT': 'Zutphen',
    'RBZWB': 'Zeeland-West-Brabant',
    'RBZWO': 'Zwolle',
    'RVBALK': 'Alkmaar',
    'RVBAMS': 'Amsterdam',
    'RVBARN': 'Arnhem',
    'RVBBRE': 'Breda',
    'RVBGRO': 'Groningen',
    'RVBHAA': 'Haarlem',
    'RVBLDN': 'Leiden',
    'RVBLEE': 'Leeuwarden',
    'RVBMID': 'Middelburg',
    'RVBROE': 'Roermond',
    'RVBROT': 'Rotterdam',
    'RVBSGR': "'s-Gravenhage",
    'RVBSHE': "'s-Hertogenbosch",
    'RVBTIL': 'Tilburg',
    'RVBUTR': 'Utrecht',
    'RVBZWO': 'Zwolle',
    'RVS': 'Raad van State',
    'TACAKN': 'NIVRA',
    'TADRAMS': 'Amsterdam',
    'TADRARL': 'Arnhem-Leeuwarden',
    'TADRARN': 'Arnhem',
    'TADRLEE': 'Leeuwarden',
    'TADRSGR': "'s-Gravenhage",
    'TADRSHE': "'s-Hertogenbosch",
    'TAHVD': 'Hof van Discipline',
    'TAKTPA': 'Akkerbouw',
    'TBBBKD': 'Bloembollenkeuringsdienst',
    'TBPSKAL': 'Skal-Tuchtgerecht',
    'TDIVBC': 'Beroepscollege',
    'TDIVTC': 'Tuchtcollege',
    'TGDKG': 'Gerechtsdeurwaarders',
    'TGFKCB': 'Kwaliteits-Controle-Bureau',
    'TGZCTG': 'Gezondheidszorg',
    'TGZRAMS': 'Amsterdam',
    'TGZREIN': 'Eindhoven',
    'TGZRGRO': 'Groningen',
    'TGZRSGR': "'s-Gravenhage",
    'TGZRZWO': 'Zwolle',
    'TNOKALK': 'Alkmaar',
    'TNOKALM': 'Almelo',
    'TNOKAMS': 'Amsterdam',
    'TNOKARN': 'Arnhem',
    'TNOKASS': 'Assen',
    'TNOKBRE': 'Breda',
    'TNOKDOR': 'Dordrecht',
    'TNOKGRO': 'Groningen',
    'TNOKHAA': 'Haarlem',
    'TNOKLEE': 'Leeuwarden',
    'TNOKMAA': 'Maastricht',
    'TNOKMID': 'Middelburg',
    'TNOKROE': 'Roermond',
    'TNOKROT': 'Rotterdam',
    'TNOKSGR': "'s-Gravenhage",
    'TNOKSHE': "'s-Hertogenbosch",
    'TNOKUTR': 'Utrecht',
    'TNOKZLY': 'Zwolle-Lelystad',
    'TNOKZUT': 'Zutphen',
    'TNORAMS': 'Amsterdam',
    'TNORARL': 'Arnhem-Leeuwarden',
    'TNORDHA': 'Den Haag',
    'TNORSHE': "'s-Hertogenbosch",
    'TPETPVE': 'Eieren',
    'TSCTS': 'Scheepvaart',
    'TVSTPV': 'Vis',
    'TVVTPVV': 'Vlees'
 }




GERECHTSCODE_INSTANTIE_MAPPING = {
    "AGAMS": "Ambtenarengerecht Amsterdam",
    "AGARN": "Ambtenarengerecht Arnhem",
    "AGGRO": "Ambtenarengerecht Groningen",
    "AGHAA": "Ambtenarengerecht Haarlem",
    "AGROE": "Ambtenarengerecht Roermond",
    "AGROT": "Ambtenarengerecht Rotterdam",
    "AGSGR": "Ambtenarengerecht 's-Gravenhage",
    "AGSHE": "Ambtenarengerecht 's-Hertogenbosch",
    "AGUTR": "Ambtenarengerecht Utrecht",
    "AGZWO": "Ambtenarengerecht Zwolle",
    "CBB": "College van Beroep voor het bedrijfsleven",
    "CRVB": "Centrale Raad van Beroep",
    "CVBSTUF": "College van Beroep Studiefinanciering",
    "DETARCO": "Tariefcommissie",
    "GHAMS": "Gerechtshof Amsterdam",
    "GHARL": "Gerechtshof Arnhem-Leeuwarden",
    "GHARN": "Gerechtshof Arnhem",
    "GHDHA": "Gerechtshof Den Haag",
    "GHLEE": "Gerechtshof Leeuwarden",
    "GHSGR": "Gerechtshof 's-Gravenhage",
    "GHSHE": "Gerechtshof 's-Hertogenbosch",
    "HR": "Hoge Raad",
    "KTGAAR": "Kantongerecht Alphen aan den Rijn",
    "KTGALK": "Kantongerecht Alkmaar",
    "KTGALM": "Kantongerecht Almelo",
    "KTGAMF": "Kantongerecht Amersfoort",
    "KTGAMS": "Kantongerecht Amsterdam",
    "KTGAPD": "Kantongerecht Apeldoorn",
    "KTGARN": "Kantongerecht Arnhem",
    "KTGASS": "Kantongerecht Assen",
    "KTGBEE": "Kantongerecht Beetsterzwaag",
    "KTGBOX": "Kantongerecht Boxmeer",
    "KTGBOZ": "Kantongerecht Bergen op Zoom",
    "KTGBRE": "Kantongerecht Breda",
    "KTGBRI": "Kantongerecht Brielle",
    "KTGDEL": "Kantongerecht Delft",
    "KTGDEV": "Kantongerecht Deventer",
    "KTGDHD": "Kantongerecht Den Helder",
    "KTGDOR": "Kantongerecht Dordrecht",
    "KTGEIN": "Kantongerecht Eindhoven",
    "KTGEMM": "Kantongerecht Emmen",
    "KTGENS": "Kantongerecht Enschede",
    "KTGGNL": "Kantongerecht Groenlo",
    "KTGGOU": "Kantongerecht Gouda",
    "KTGGRC": "Kantongerecht Gorinchem",
    "KTGGRO": "Kantongerecht Groningen",
    "KTGHAA": "Kantongerecht Haarlem",
    "KTGHAR": "Kantongerecht Harderwijk",
    "KTGHFD": "Kantongerecht Hoofddorp",
    "KTGHIL": "Kantongerecht Hilversum",
    "KTGHMD": "Kantongerecht Helmond",
    "KTGHRL": "Kantongerecht Heerlen",
    "KTGHRN": "Kantongerecht Hoorn",
    "KTGHRV": "Kantongerecht Heerenveen",
    "KTGLDN": "Kantongerecht Leiden",
    "KTGLEE": "Kantongerecht Leeuwarden",
    "KTGLLY": "Kantongerecht Lelystad",
    "KTGMAA": "Kantongerecht Maastricht",
    "KTGMEP": "Kantongerecht Meppel",
    "KTGMID": "Kantongerecht Middelburg",
    "KTGNMG": "Kantongerecht Nijmegen",
    "KTGOBL": "Kantongerecht Oud-Beijerland",
    "KTGOOS": "Kantongerecht Oostburg",
    "KTGPAR": "Kantongerecht Parimaribo",
    "KTGROE": "Kantongerecht Roermond",
    "KTGROT": "Kantongerecht Rotterdam",
    "KTGSCH": "Kantongerecht Schiedam",
    "KTGSGR": "Kantongerecht 's-Gravenhage",
    "KTGSHE": "Kantongerecht 's-Hertogenbosch",
    "KTGSIT": "Kantongerecht Sittard",
    "KTGSNK": "Kantongerecht Sneek",
    "KTGSOM": "Kantongerecht Sommelsdijk",
    "KTGSTW": "Kantongerecht Steenwijk",
    "KTGTIE": "Kantongerecht Tiel",
    "KTGTIL": "Kantongerecht Tilburg",
    "KTGTRB": "Kantongerecht Terborg",
    "KTGTRN": "Kantongerecht Terneuzen",
    "KTGUTR": "Kantongerecht Utrecht",
    "KTGVEE": "Kantongerecht Veendam",
    "KTGVEN": "Kantongerecht Venlo",
    "KTGWAG": "Kantongerecht Wageningen",
    "KTGWIN": "Kantongerecht Winschoten",
    "KTGZAA": "Kantongerecht Zaandam",
    "KTGZEV": "Kantongerecht Zevenbergen",
    "KTGZIE": "Kantongerecht Zierikzee",
    "KTGZUI": "Kantongerecht Zuidbroek",
    "KTGZUT": "Kantongerecht Zutphen",
    "KTGZWO": "Kantongerecht Zwolle",
    "OCHM": "Constitutioneel Hof Sint Maarten",
    "OGAACMB": "Gerecht in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "OGANA": "Gerecht in Ambtenarenzaken van de Nederlandse Antillen",
    "OGEAA": "Gerecht in Eerste Aanleg van Aruba",
    "OGEAB": "Gerecht in Eerste Aanleg Bonaire",
    "OGEABES": "Gerecht in eerste aanleg van Bonaire, Sint Eustatius en Saba",
    "OGEAC": "Gerecht in eerste aanleg van Curacao",
    "OGEAM": "Gerecht in eerste aanleg van Sint Maarten",
    "OGEANA": "Gerecht in Eerste Aanleg van de Nederlandse Antillen",
    "OGHACMB": "Gemeenschappelijk Hof van Justitie van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "OGHNAA": "Gemeenschappelijk Hof van Justitie van de Nederlandse Antillen en Aruba",
    "OHJNA": "Hof van Justitie van de Nederlandse Antillen",
    "ORBAACM": "Raad van Beroep in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "ORBANAA": "Raad van Beroep in Ambtenarenzaken (Nederlandse Antillen en Aruba)",
    "ORBBACM": "Raad van Beroep voor Belastingzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "ORBBNAA": "Raad van Beroep voor Belastingzaken (Nederlandse Antillen en Aruba)",
    "PHR": "Parket bij de Hoge Raad",
    "RBALK": "Rechtbank Alkmaar",
    "RBALM": "Rechtbank Almelo",
    "RBAMS": "Rechtbank Amsterdam",
    "RBARN": "Rechtbank Arnhem",
    "RBASS": "Rechtbank Assen",
    "RBBRE": "Rechtbank Breda",
    "RBDHA": "Rechtbank Den Haag",
    "RBDOR": "Rechtbank Dordrecht",
    "RBGEL": "Rechtbank Gelderland",
    "RBGRO": "Rechtbank Groningen",
    "RBHAA": "Rechtbank Haarlem",
    "RBLEE": "Rechtbank Leeuwarden",
    "RBLIM": "Rechtbank Limburg",
    "RBMAA": "Rechtbank Maastricht",
    "RBMID": "Rechtbank Middelburg",
    "RBMNE": "Rechtbank Midden-Nederland",
    "RBNHO": "Rechtbank Noord-Holland",
    "RBNNE": "Rechtbank Noord-Nederland",
    "RBOBR": "Rechtbank Oost-Brabant",
    "RBONE": "Rechtbank Oost-Nederland",
    "RBOVE": "Rechtbank Overijssel",
    "RBROE": "Rechtbank Roermond",
    "RBROT": "Rechtbank Rotterdam",
    "RBSGR": "Rechtbank 's-Gravenhage",
    "RBSHE": "Rechtbank 's-Hertogenbosch",
    "RBUTR": "Rechtbank Utrecht",
    "RBZLY": "Rechtbank Zwolle-Lelystad",
    "RBZUT": "Rechtbank Zutphen",
    "RBZWB": "Rechtbank Zeeland-West-Brabant",
    "RBZWO": "Rechtbank Zwolle",
    "RVBALK": "Raad van beroep Alkmaar",
    "RVBAMS": "Raad van beroep Amsterdam",
    "RVBARN": "Raad van beroep Arnhem",
    "RVBBRE": "Raad van beroep Breda",
    "RVBGRO": "Raad van beroep Groningen",
    "RVBHAA": "Raad van beroep Haarlem",
    "RVBLDN": "Raad van beroep Leiden",
    "RVBLEE": "Raad van beroep Leeuwarden",
    "RVBMID": "Raad van beroep Middelburg",
    "RVBROE": "Raad van beroep Roermond",
    "RVBROT": "Raad van beroep Rotterdam",
    "RVBSGR": "Raad van beroep 's-Gravenhage",
    "RVBSHE": "Raad van beroep 's-Hertogenbosch",
    "RVBTIL": "Raad van beroep Tilburg",
    "RVBUTR": "Raad van beroep Utrecht",
    "RVBZWO": "Raad van beroep Zwolle",
    "RVS": "Raad van State",
    "TACAKN": "Accountantskamer NIVRA",
    "TADRAMS": "Raad van Discipline Amsterdam",
    "TADRARL": "Raad van Discipline Arnhem-Leeuwarden",
    "TADRARN": "Raad van Discipline Arnhem",
    "TADRLEE": "Raad van Discipline Leeuwarden",
    "TADRSGR": "Raad van Discipline 's-Gravenhage",
    "TADRSHE": "Raad van Discipline 's-Hertogenbosch",
    "TAHVD": "Hof van Discipline",
    "TAKTPA": "Tuchtgerecht Productschap Akkerbouw",
    "TBBBKD": "Tuchtgerecht Bloembollenkeuringsdienst",
    "TBPSKAL": "Skal-Tuchtgerecht",
    "TDIVBC": "Veterinair Beroepscollege",
    "TDIVTC": "Veterinair Tuchtcollege",
    "TGDKG": "Kamer voor Gerechtsdeurwaarders",
    "TGFKCB": "Tuchtgerecht Kwaliteits-Controle-Bureau",
    "TGZCTG": "Centraal Tuchtcollege voor de Gezondheidszorg",
    "TGZRAMS": "Regionaal Tuchtcollege voor de Gezondheidszorg Amsterdam",
    "TGZREIN": "Regionaal Tuchtcollege voor de Gezondheidszorg Eindhoven",
    "TGZRGRO": "Regionaal Tuchtcollege voor de Gezondheidszorg Groningen",
    "TGZRSGR": "Regionaal Tuchtcollege voor de Gezondheidszorg 's-Gravenhage",
    "TGZRZWO": "Regionaal Tuchtcollege voor de Gezondheidszorg Zwolle",
    "TNOKALK": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Alkmaar",
    "TNOKALM": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Almelo",
    "TNOKAMS": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Amsterdam",
    "TNOKARN": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Arnhem",
    "TNOKASS": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Assen",
    "TNOKBRE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Breda",
    "TNOKDOR": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Dordrecht",
    "TNOKGRO": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Groningen",
    "TNOKHAA": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Haarlem",
    "TNOKLEE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Leeuwarden",
    "TNOKMAA": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Maastricht",
    "TNOKMID": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Middelburg",
    "TNOKROE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Roermond",
    "TNOKROT": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Rotterdam",
    "TNOKSGR": "Kamer van Toezicht over de notarissen en kandidaat-notarissen 's-Gravenhage",
    "TNOKSHE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen 's-Hertogenbosch",
    "TNOKUTR": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Utrecht",
    "TNOKZLY": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Zwolle-Lelystad",
    "TNOKZUT": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Zutphen",
    "TNORAMS": "Kamer voor het notariaat in het ressort Amsterdam",
    "TNORARL": "Kamer voor het notariaat in het ressort Arnhem-Leeuwarden",
    "TNORDHA": "Kamer voor het notariaat in het ressort Den Haag",
    "TNORSHE": "Kamer voor het notariaat in het ressort 's-Hertogenbosch",
    "TPETPVE": "Tuchtgerecht Productschap Pluimvee en Eieren",
    "TSCTS": "Tuchtcollege voor de Scheepvaart",
    "TVSTPV": "Tuchtgerecht Productschap Vis",
    "TVVTPVV": "Tuchtgerecht Productschap Vee en Vlees"
}


EXTRA_MAPPER = {
    "Rechtbank Den Haag": "Den Haag",
    "Gerechtshof Den Haag": "Den Haag",
    "Hoge Raad": "Den Haag",
    "Parket bij de Hoge Raad": "Den Haag",
    "Centrale Raad van Beroep": "Utrecht",
    "Raad van State": "Den Haag",
    "College van Beroep voor het bedrijfsleven": "Den Haag",
    "Gemeenschappelijk Hof van Justitie van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Gerecht in eerste aanleg van Curacao": "Nederlandse Antillen",
    "Gerecht in eerste aanleg van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Gerecht in Eerste Aanleg van Aruba": "Nederlandse Antillen",
    "Gerecht in eerste aanleg van Sint Maarten": "Nederlandse Antillen",
    "Gemeenschappelijk Hof van Justitie van de Nederlandse Antillen en Aruba": "Nederlandse Antillen",
    "Gerecht in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Raad van Beroep in Ambtenarenzaken (Nederlandse Antillen en Aruba)": "Nederlandse Antillen",
    "Raad van Beroep in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Gerecht in Eerste Aanleg van de Nederlandse Antillen": "Nederlandse Antillen",
}

LOCATIE_PROVINCIE_MAPPER = {
    "Noord-Nederland": ["Friesland", "Groningen"],
    "Zutphen": ["Gelderland"],
    "Zeeland-West-Brabant": ["Zeeland, Noord-Brabant"],
    "Amsterdam": ["Noord-Holland"],
    "Midden-Nederland": ["Utrecht", "Flevoland"],
    "Rotterdam": ["Zuid-Holland"],
    "Nederlandse Antillen": [],
    "Den Haag": ["Zuid-Holland"],
    "Zwolle-Lelystad": ["Overijssel", "Flevoland"],
    "Utrecht": ["Utrecht"],
    "Gelderland": ["Gelderland"],
    "Arnhem-Leeuwarden": ["Gelderland", "Overijssel", "Friesland"],
    "Leeuwarden": ["Friesland"],
    "Middelburg": ["Zeeland"],
    "Overijssel": ["Overijssel"],
    "Noord-Holland": ["Noord-Holland"],
    "Breda": ["Noord-Brabant"],
    "Almelo": ["Overijssel"],
    "'s-Gravenhage": ["Zuid-Holland"],
    "Maastricht": ["Limburg"],
    "'s-Hertogenbosch": ["Noord-Holland"],
    "Oost-Brabant": ["Noord-Brabant"],
    "Haarlem": ["Noord-Holland"],
    "Alkmaar": ["Noord-Holland"],
    "Assen": ["Drenthe"],
    "Limburg": ["Limburg"],
    "Roermond": ["Limburg"],
    "Groningen": ["Groningen"],
    "Arnhem": ["Gelderland"],
    "Dordrecht": ["Zuid-Holland"],
    "Oost-Nederland": ["Overijssel", "Gelderland"],
    "Zwolle": ["Overijssel"]
}


DRUGS_AND_PRECURSORS_TABLEAU = {
    "MDMA": {
        "altnames": ['MDMA', 'Methylenedioxymethamphetamine'],
        "precursors": {
                "Bromosafrole": {
                    "altnames": ['bromosafrole', 'bromosafrool'],
                    "preprecursors": {}
                }, 
                "PMK": {
                    "altnames": ['PMK', 'piperonylmethylketon', 'MDP2P', 'MDP-2-P'],
                    "preprecursors": {
                        "safrol": ['safrol', 'isosafrol', 'safrool', 'isosafrool', 'safrole', 'sassafras olie', 'safrole olie'],
                        "piperonal": ['piperonal', 'piperonalglycidaat', 'heliotropine', 'heliotropin'],
                        "PMK glycide zuur": ["pmk glycide zuur"],
                        "P2NP": ["fenylnitropropaan", "P2NP"],
                        "Helional": ["helional"]
                    }
                },
                "N-t-BOC-MDMA": {
                    "altnames": ["N-t-BOC-MDMA", "N t BOC MDMA", "N t BOC MDMA"],
                    "preprecursors": {}
                }
        }
    },
    "Methamphetamine": {
        "altnames": ['Methamfetamine', 'Methamphetamine', 'Meth'],
        "precursors": {
            "Pseudoephedrine": {
                    "altnames": ["pseudoephedrine", "pseudoefedrine"],
                    "preprecursors": {}
            },
            "Ephedrine": {
                    "altnames": ['ephedrine', 'efedrine'],
                    "preprecursors": {
                        "Fenylacetolcarbinol": ["Phenylacetylcarbinol", "fenylacetolcarbinol" , "LPAC", "L-PAC", "PAC"],
                    }
            },
            "Chloropseudoephedrine": {
                    "altnames": ["chloropseudoephedrine", "chloropseudoefedrine"],
                    "preprecursors": {}
            },
            "Chloroephedrine": {
                    "altnames": ["chloroephedrine", "chloroefedrine"],
                    "preprecursors": {}
            },
             "BMK": {
                "altnames": ["BMK", 'benzylmethylketon', "P2P", "P-2-P"],
                "preprecursors": {
                    "MAPA": ["MAPA"],
                    "APAA": ["APAA"],
                    "BMK glycide zuur": ["BMK glycide zuur"],
                    "Benzaldehyde": ["Benzaldehyde"],
                    "Fenylnitropropaan": ["Fenylnitropropaan"],
                    "APAAN": ["APAAN"],
                    "Benzylcyanide": ["Benzylcyanide"],
                    "Fenylazijnzuur": ["Fenylazijnzuur", "PAA", "phenylacetic acid"]
                }
            },           
            "N-t-BOC-methamphetamine": {
                "altnames": ["N-t-BOC-methamphetamine", "N-t-BOC-meth", "N t BOC meth"],
                "preprecursors": {}
            }
        },
    },
    "Amphetamine": {
        "altnames": ['Amfetamine', 'Amphetamine'],
        "precursors": {
            "BMK": {
                "altnames": ["BMK", 'benzylmethylketon', "P2P", "P-2-P"],
                "preprecursors": {
                    "MAPA": ["MAPA"],
                    "APAA": ["APAA"],
                    "BMK glycide zuur": ["BMK glycide zuur"],
                    "Benzaldehyde": ["Benzaldehyde"],
                    "Fenylnitropropaan": ["Fenylnitropropaan"],
                    "APAAN": ["APAAN"],
                    "Benzylcyanide": ["Benzylcyanide"],
                    "Fenylazijnzuur": ["Fenylazijnzuur", "PAA", "phenylacetic acid"]
                }                
            } 
        }
    }
}


# Index(['date', 'case_id', 'mdma_count', 'bromosafrole_count', 'pmk_count',
#        'safrol_count', 'piperonal_count', 'pmk glycide zuur_count',
#        'p2np_count', 'helional_count', 'n-t-boc-mdma_count',
#        'methamphetamine_count', 'pseudoephedrine_count', 'ephedrine_count',
#        'fenylacetolcarbinol_count', 'chloropseudoephedrine_count',
#        'chloroephedrine_count', 'bmk_count_x', 'mapa_count_x', 'apaa_count_x',
#        'bmk glycide zuur_count_x', 'benzaldehyde_count_x',
#        'fenylnitropropaan_count_x', 'apaan_count_x', 'benzylcyanide_count_x',
#        'fenylazijnzuur_count_x', 'n-t-boc-methamphetamine_count',
#        'amphetamine_count', 'bmk_count_y', 'mapa_count_y', 'apaa_count_y',
#        'bmk glycide zuur_count_y', 'benzaldehyde_count_y',
#        'fenylnitropropaan_count_y', 'apaan_count_y', 'benzylcyanide_count_y',
#        'fenylazijnzuur_count_y'],
#       dtype='object')