version: '3.8'

services:
  redis:
    image: redis:6-alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
  
  celery:
    build: .
    command: celery --app dsp worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - redis