DRUGS_AND_PRECURSORS = {
    "safrol": ['safrol', 'isosafrol', 'safrool', 'isosafrool'],
    "piperonal": ['piperonal', 'piperonalglycidaat'],
    "PMK": ['PMK','piperonylmethylketon'],
    "BMK": ['BMK', 'BenzylMethylKeton'],
    "apaan": ['apaan','Alpha-Phenylacetoacetonitrile', 'AlphaPhenylacetoacetonitrile'],
    "GBL": ['GBL', 'Gamma-butyrolacton'],
    "MDP2P": ['MDP2P'],
    "efedrine": ['Efedrine', 'Ephedrine'],
    "ergotamine": ['Ergotamine'],
    "lyserginezuur": ['Lyserginezuur'],
    "methamphetamine": ['Methamfetamine', 'Methamphetamine'],
    "MDMA": ['MDMA', 'Methylenedioxymethamphetamine'],
    "amphetamine": ['Amfetamine', 'Amphetamine'],
    "cocaine": ['Cocaïne', 'Cocaine', 'Coke'],
    "XTC": ['XTC', 'ecstasy'],
    "GHB": ['GHB', 'gamma-hydroxyboterzuur', '4-hydroxybutaanzuur']
}


a = '''CREATE TABLE IF NOT EXISTS public.court_verdicts (
        case_id varchar(100) NOT NULL,
        case_text text,
        PRIMARY KEY (case_id)
    )'''

b = '''CREATE TABLE IF NOT EXISTS public.case_data (
        case_id varchar(100) NOT NULL,
        titel varchar(255),
        court_datum date,
        uitspraak_type varchar(30),
        gerechtelijk_product_type varchar(30),
        procedure_soort varchar(100),
        rechtsgebieden varchar(100),
        PRIMARY KEY (case_id)
    )'''

c = '''CREATE TABLE IF NOT EXISTS public.sewer (
        year integer,
        cocaine numeric,
        amphetamine numeric,
        MDMA numeric,
        methamphetamine numeric
    )'''


d = '''CREATE TABLE IF NOT EXISTS public.drug_prevalence_count (
        case_id varchar(100) NOT NULL,
        court_datum date, 
        safrol integer,
        piperonal integer,
        PMK integer,
        BMK integer,
        apaan integer,
        GBL integer, 
        MDP2P integer,
        efedrine integer, 
        ergotamine integer,
        lyserginezuur integer,
        methamphetamine integer,
        MDMA integer,
        amphetamine integer,
        cocaine integer,
        XTC integer,
        GHB integer,
        PRIMARY KEY (case_id)
    )'''

queries = [a, b, c, d]






GERECHTSCODE_INSTANTIE_MAPPING = {
    "AGAMS": "Ambtenarengerecht Amsterdam",
    "AGARN": "Ambtenarengerecht Arnhem",
    "AGGRO": "Ambtenarengerecht Groningen",
    "AGHAA": "Ambtenarengerecht Haarlem",
    "AGROE": "Ambtenarengerecht Roermond",
    "AGROT": "Ambtenarengerecht Rotterdam",
    "AGSGR": "Ambtenarengerecht 's-Gravenhage",
    "AGSHE": "Ambtenarengerecht 's-Hertogenbosch",
    "AGUTR": "Ambtenarengerecht Utrecht",
    "AGZWO": "Ambtenarengerecht Zwolle",
    "CBB": "College van Beroep voor het bedrijfsleven",
    "CRVB": "Centrale Raad van Beroep",
    "CVBSTUF": "College van Beroep Studiefinanciering",
    "DETARCO": "Tariefcommissie",
    "GHAMS": "Gerechtshof Amsterdam",
    "GHARL": "Gerechtshof Arnhem-Leeuwarden",
    "GHARN": "Gerechtshof Arnhem",
    "GHDHA": "Gerechtshof Den Haag",
    "GHLEE": "Gerechtshof Leeuwarden",
    "GHSGR": "Gerechtshof 's-Gravenhage",
    "GHSHE": "Gerechtshof 's-Hertogenbosch",
    "HR": "Hoge Raad",
    "KTGAAR": "Kantongerecht Alphen aan den Rijn",
    "KTGALK": "Kantongerecht Alkmaar",
    "KTGALM": "Kantongerecht Almelo",
    "KTGAMF": "Kantongerecht Amersfoort",
    "KTGAMS": "Kantongerecht Amsterdam",
    "KTGAPD": "Kantongerecht Apeldoorn",
    "KTGARN": "Kantongerecht Arnhem",
    "KTGASS": "Kantongerecht Assen",
    "KTGBEE": "Kantongerecht Beetsterzwaag",
    "KTGBOX": "Kantongerecht Boxmeer",
    "KTGBOZ": "Kantongerecht Bergen op Zoom",
    "KTGBRE": "Kantongerecht Breda",
    "KTGBRI": "Kantongerecht Brielle",
    "KTGDEL": "Kantongerecht Delft",
    "KTGDEV": "Kantongerecht Deventer",
    "KTGDHD": "Kantongerecht Den Helder",
    "KTGDOR": "Kantongerecht Dordrecht",
    "KTGEIN": "Kantongerecht Eindhoven",
    "KTGEMM": "Kantongerecht Emmen",
    "KTGENS": "Kantongerecht Enschede",
    "KTGGNL": "Kantongerecht Groenlo",
    "KTGGOU": "Kantongerecht Gouda",
    "KTGGRC": "Kantongerecht Gorinchem",
    "KTGGRO": "Kantongerecht Groningen",
    "KTGHAA": "Kantongerecht Haarlem",
    "KTGHAR": "Kantongerecht Harderwijk",
    "KTGHFD": "Kantongerecht Hoofddorp",
    "KTGHIL": "Kantongerecht Hilversum",
    "KTGHMD": "Kantongerecht Helmond",
    "KTGHRL": "Kantongerecht Heerlen",
    "KTGHRN": "Kantongerecht Hoorn",
    "KTGHRV": "Kantongerecht Heerenveen",
    "KTGLDN": "Kantongerecht Leiden",
    "KTGLEE": "Kantongerecht Leeuwarden",
    "KTGLLY": "Kantongerecht Lelystad",
    "KTGMAA": "Kantongerecht Maastricht",
    "KTGMEP": "Kantongerecht Meppel",
    "KTGMID": "Kantongerecht Middelburg",
    "KTGNMG": "Kantongerecht Nijmegen",
    "KTGOBL": "Kantongerecht Oud-Beijerland",
    "KTGOOS": "Kantongerecht Oostburg",
    "KTGPAR": "Kantongerecht Parimaribo",
    "KTGROE": "Kantongerecht Roermond",
    "KTGROT": "Kantongerecht Rotterdam",
    "KTGSCH": "Kantongerecht Schiedam",
    "KTGSGR": "Kantongerecht 's-Gravenhage",
    "KTGSHE": "Kantongerecht 's-Hertogenbosch",
    "KTGSIT": "Kantongerecht Sittard",
    "KTGSNK": "Kantongerecht Sneek",
    "KTGSOM": "Kantongerecht Sommelsdijk",
    "KTGSTW": "Kantongerecht Steenwijk",
    "KTGTIE": "Kantongerecht Tiel",
    "KTGTIL": "Kantongerecht Tilburg",
    "KTGTRB": "Kantongerecht Terborg",
    "KTGTRN": "Kantongerecht Terneuzen",
    "KTGUTR": "Kantongerecht Utrecht",
    "KTGVEE": "Kantongerecht Veendam",
    "KTGVEN": "Kantongerecht Venlo",
    "KTGWAG": "Kantongerecht Wageningen",
    "KTGWIN": "Kantongerecht Winschoten",
    "KTGZAA": "Kantongerecht Zaandam",
    "KTGZEV": "Kantongerecht Zevenbergen",
    "KTGZIE": "Kantongerecht Zierikzee",
    "KTGZUI": "Kantongerecht Zuidbroek",
    "KTGZUT": "Kantongerecht Zutphen",
    "KTGZWO": "Kantongerecht Zwolle",
    "OCHM": "Constitutioneel Hof Sint Maarten",
    "OGAACMB": "Gerecht in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "OGANA": "Gerecht in Ambtenarenzaken van de Nederlandse Antillen",
    "OGEAA": "Gerecht in Eerste Aanleg van Aruba",
    "OGEAB": "Gerecht in Eerste Aanleg Bonaire",
    "OGEABES": "Gerecht in eerste aanleg van Bonaire, Sint Eustatius en Saba",
    "OGEAC": "Gerecht in eerste aanleg van Curacao",
    "OGEAM": "Gerecht in eerste aanleg van Sint Maarten",
    "OGEANA": "Gerecht in Eerste Aanleg van de Nederlandse Antillen",
    "OGHACMB": "Gemeenschappelijk Hof van Justitie van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "OGHNAA": "Gemeenschappelijk Hof van Justitie van de Nederlandse Antillen en Aruba",
    "OHJNA": "Hof van Justitie van de Nederlandse Antillen",
    "ORBAACM": "Raad van Beroep in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "ORBANAA": "Raad van Beroep in Ambtenarenzaken (Nederlandse Antillen en Aruba)",
    "ORBBACM": "Raad van Beroep voor Belastingzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba",
    "ORBBNAA": "Raad van Beroep voor Belastingzaken (Nederlandse Antillen en Aruba)",
    "PHR": "Parket bij de Hoge Raad",
    "RBALK": "Rechtbank Alkmaar",
    "RBALM": "Rechtbank Almelo",
    "RBAMS": "Rechtbank Amsterdam",
    "RBARN": "Rechtbank Arnhem",
    "RBASS": "Rechtbank Assen",
    "RBBRE": "Rechtbank Breda",
    "RBDHA": "Rechtbank Den Haag",
    "RBDOR": "Rechtbank Dordrecht",
    "RBGEL": "Rechtbank Gelderland",
    "RBGRO": "Rechtbank Groningen",
    "RBHAA": "Rechtbank Haarlem",
    "RBLEE": "Rechtbank Leeuwarden",
    "RBLIM": "Rechtbank Limburg",
    "RBMAA": "Rechtbank Maastricht",
    "RBMID": "Rechtbank Middelburg",
    "RBMNE": "Rechtbank Midden-Nederland",
    "RBNHO": "Rechtbank Noord-Holland",
    "RBNNE": "Rechtbank Noord-Nederland",
    "RBOBR": "Rechtbank Oost-Brabant",
    "RBONE": "Rechtbank Oost-Nederland",
    "RBOVE": "Rechtbank Overijssel",
    "RBROE": "Rechtbank Roermond",
    "RBROT": "Rechtbank Rotterdam",
    "RBSGR": "Rechtbank 's-Gravenhage",
    "RBSHE": "Rechtbank 's-Hertogenbosch",
    "RBUTR": "Rechtbank Utrecht",
    "RBZLY": "Rechtbank Zwolle-Lelystad",
    "RBZUT": "Rechtbank Zutphen",
    "RBZWB": "Rechtbank Zeeland-West-Brabant",
    "RBZWO": "Rechtbank Zwolle",
    "RVBALK": "Raad van beroep Alkmaar",
    "RVBAMS": "Raad van beroep Amsterdam",
    "RVBARN": "Raad van beroep Arnhem",
    "RVBBRE": "Raad van beroep Breda",
    "RVBGRO": "Raad van beroep Groningen",
    "RVBHAA": "Raad van beroep Haarlem",
    "RVBLDN": "Raad van beroep Leiden",
    "RVBLEE": "Raad van beroep Leeuwarden",
    "RVBMID": "Raad van beroep Middelburg",
    "RVBROE": "Raad van beroep Roermond",
    "RVBROT": "Raad van beroep Rotterdam",
    "RVBSGR": "Raad van beroep 's-Gravenhage",
    "RVBSHE": "Raad van beroep 's-Hertogenbosch",
    "RVBTIL": "Raad van beroep Tilburg",
    "RVBUTR": "Raad van beroep Utrecht",
    "RVBZWO": "Raad van beroep Zwolle",
    "RVS": "Raad van State",
    "TACAKN": "Accountantskamer NIVRA",
    "TADRAMS": "Raad van Discipline Amsterdam",
    "TADRARL": "Raad van Discipline Arnhem-Leeuwarden",
    "TADRARN": "Raad van Discipline Arnhem",
    "TADRLEE": "Raad van Discipline Leeuwarden",
    "TADRSGR": "Raad van Discipline 's-Gravenhage",
    "TADRSHE": "Raad van Discipline 's-Hertogenbosch",
    "TAHVD": "Hof van Discipline",
    "TAKTPA": "Tuchtgerecht Productschap Akkerbouw",
    "TBBBKD": "Tuchtgerecht Bloembollenkeuringsdienst",
    "TBPSKAL": "Skal-Tuchtgerecht",
    "TDIVBC": "Veterinair Beroepscollege",
    "TDIVTC": "Veterinair Tuchtcollege",
    "TGDKG": "Kamer voor Gerechtsdeurwaarders",
    "TGFKCB": "Tuchtgerecht Kwaliteits-Controle-Bureau",
    "TGZCTG": "Centraal Tuchtcollege voor de Gezondheidszorg",
    "TGZRAMS": "Regionaal Tuchtcollege voor de Gezondheidszorg Amsterdam",
    "TGZREIN": "Regionaal Tuchtcollege voor de Gezondheidszorg Eindhoven",
    "TGZRGRO": "Regionaal Tuchtcollege voor de Gezondheidszorg Groningen",
    "TGZRSGR": "Regionaal Tuchtcollege voor de Gezondheidszorg 's-Gravenhage",
    "TGZRZWO": "Regionaal Tuchtcollege voor de Gezondheidszorg Zwolle",
    "TNOKALK": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Alkmaar",
    "TNOKALM": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Almelo",
    "TNOKAMS": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Amsterdam",
    "TNOKARN": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Arnhem",
    "TNOKASS": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Assen",
    "TNOKBRE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Breda",
    "TNOKDOR": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Dordrecht",
    "TNOKGRO": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Groningen",
    "TNOKHAA": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Haarlem",
    "TNOKLEE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Leeuwarden",
    "TNOKMAA": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Maastricht",
    "TNOKMID": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Middelburg",
    "TNOKROE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Roermond",
    "TNOKROT": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Rotterdam",
    "TNOKSGR": "Kamer van Toezicht over de notarissen en kandidaat-notarissen 's-Gravenhage",
    "TNOKSHE": "Kamer van Toezicht over de notarissen en kandidaat-notarissen 's-Hertogenbosch",
    "TNOKUTR": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Utrecht",
    "TNOKZLY": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Zwolle-Lelystad",
    "TNOKZUT": "Kamer van Toezicht over de notarissen en kandidaat-notarissen Zutphen",
    "TNORAMS": "Kamer voor het notariaat in het ressort Amsterdam",
    "TNORARL": "Kamer voor het notariaat in het ressort Arnhem-Leeuwarden",
    "TNORDHA": "Kamer voor het notariaat in het ressort Den Haag",
    "TNORSHE": "Kamer voor het notariaat in het ressort 's-Hertogenbosch",
    "TPETPVE": "Tuchtgerecht Productschap Pluimvee en Eieren",
    "TSCTS": "Tuchtcollege voor de Scheepvaart",
    "TVSTPV": "Tuchtgerecht Productschap Vis",
    "TVVTPVV": "Tuchtgerecht Productschap Vee en Vlees"
}


EXTRA_MAPPER = {
    "Rechtbank Den Haag": "Den Haag",
    "Gerechtshof Den Haag": "Den Haag",
    "Hoge Raad": "Den Haag",
    "Parket bij de Hoge Raad": "Den Haag",
    "Centrale Raad van Beroep": "Utrecht",
    "Raad van State": "Den Haag",
    "College van Beroep voor het bedrijfsleven": "Den Haag",
    "Gemeenschappelijk Hof van Justitie van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Gerecht in eerste aanleg van Curacao": "Nederlandse Antillen",
    "Gerecht in eerste aanleg van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Gerecht in Eerste Aanleg van Aruba": "Nederlandse Antillen",
    "Gerecht in eerste aanleg van Sint Maarten": "Nederlandse Antillen",
    "Gemeenschappelijk Hof van Justitie van de Nederlandse Antillen en Aruba": "Nederlandse Antillen",
    "Gerecht in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Raad van Beroep in Ambtenarenzaken (Nederlandse Antillen en Aruba)": "Nederlandse Antillen",
    "Raad van Beroep in Ambtenarenzaken van Aruba, Curacao, Sint Maarten en van Bonaire, Sint Eustatius en Saba": "Nederlandse Antillen",
    "Gerecht in Eerste Aanleg van de Nederlandse Antillen": "Nederlandse Antillen",
}

LOCATIE_PROVINCIE_MAPPER = {
    "Noord-Nederland": ["Friesland", "Groningen"],
    "Zutphen": ["Gelderland"],
    "Zeeland-West-Brabant": ["Zeeland, Noord-Brabant"],
    "Amsterdam": ["Noord-Holland"],
    "Midden-Nederland": ["Utrecht", "Flevoland"],
    "Rotterdam": ["Zuid-Holland"],
    "Nederlandse Antillen": [],
    "Den Haag": ["Zuid-Holland"],
    "Zwolle-Lelystad": ["Overijssel", "Flevoland"],
    "Utrecht": ["Utrecht"],
    "Gelderland": ["Gelderland"],
    "Arnhem-Leeuwarden": ["Gelderland", "Overijssel", "Friesland"],
    "Leeuwarden": ["Friesland"],
    "Middelburg": ["Zeeland"],
    "Overijssel": ["Overijssel"],
    "Noord-Holland": ["Noord-Holland"],
    "Breda": ["Noord-Brabant"],
    "Almelo": ["Overijssel"],
    "'s-Gravenhage": ["Zuid-Holland"],
    "Maastricht": ["Limburg"],
    "'s-Hertogenbosch": ["Noord-Holland"],
    "Oost-Brabant": ["Noord-Brabant"],
    "Haarlem": ["Noord-Holland"],
    "Alkmaar": ["Noord-Holland"],
    "Assen": ["Drenthe"],
    "Limburg": ["Limburg"],
    "Roermond": ["Limburg"],
    "Groningen": ["Groningen"],
    "Arnhem": ["Gelderland"],
    "Dordrecht": ["Zuid-Holland"],
    "Oost-Nederland": ["Overijssel", "Gelderland"],
    "Zwolle": ["Overijssel"]
}